blog/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('search/<str:q>/', views.PostSearch.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('category/<str:slug>/', views.category_page),
    path('', views.PostList.as_view()),
    path('<int:pk>/', views.PostDetail.as_view())
    # path('<int:pk>/', views.single_post_pages),
    # path('', views.index),
]

do_it_django_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('single_pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
import os

class Category(models.Model):
    name = models.CharField(max_length=50, unique = True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'
    
    class Meta:
        verbose_name_plural = 'Categories'

class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = MarkdownxField()
    
    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    author = models.ForeignKey(User, null = True, on_delete=models.SET_NULL)
    
    category = models.ForeignKey(Category, null= True, blank= True, on_delete=models.SET_NULL)
        
    def __str__(self):
        return f'[{self.pk}] {self.title} :: {self.author}'
    
    def get_absolute_url(self):
        return f'/blog/{self.pk}/'
    
    def get_file_name(self):
        return os.path.basename(self.file_upload.name)
    
    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]

    def get_content_markdown(self):
        return markdown(self.content)
    
    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_absolute_url()
        else:
            return f'https://ui-avatars.com/api/?name={self.author}'
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'
    
    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'
    
    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            # return 'https://doitdjango.com/avatar/id/1814/72b03fe07df3197f/svg/{self.author.email}'
            return f'https://ui-avatars.com/api/?name={self.author}'

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404
from django.db.models import Q
from .models import Post, Category, Comment
from .forms import CommentForm
from django.core.exceptions import PermissionDenied

class PostList(ListView):
    model = Post
    ordering = '-pk'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        
        return context
    
def category_page(request, slug):
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)
        
    return render(
        request,
        'blog/post_list.html',
        {
            'post_list': post_list,
            'categories': Category.objects.all(),
            'no_category_post_count': Post.objects.filter(category=None).count(),
            'category': category,
        }
    )
    
class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        context['comment_form'] = CommentForm
        
        return context

class PostCreate(LoginRequiredMixin, UserPassesTestMixin ,CreateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff
    
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            return super(PostCreate, self).form_valid(form)
        else:
            return redirect('/blog/')

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']

    template_name = 'blog/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)
        
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied
        
class PostSearch(PostList):
    paginate_by = None
    
    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q)).distinct() ## 쿼리조건 시 .(dot)이 아닌 __(two underbar)를 사용
        return post_list
    
    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'
        
        return context

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}Blog{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/bootstrap/bootstrap.min.css' %}" media="screen">
    <script src="https://kit.fontawesome.com/7ec0f23614.js" crossorigin="anonymous"></script>
</head>

<body>

    {% include 'blog/navbar.html' %}

    <div class="container my-3">
        <div class="row">
            <div class="col-md-8 col-lg-9" id="main-area">
                {% block main_area %}
                {% endblock %}
            </div>

            <div class="col-md-4 col-lg-3">
                <!-- Search widget-->
                <div class="card mb-4">
                    <div class="card-header">Search</div>
                    <div class="card-body">
                        <div class="input-group">
                            <input class="form-control" type="text" placeholder="Enter search term..." id="search-input"
                                aria-label="Enter search term..." aria-describedby="button-search" />
                            <button class="btn btn-primary" id="button-search" type="button" onclick="searchPost();">Search</button>
                        </div>
                    </div>
                </div>

                <!-- Categories widget-->
                <div class="card mb-4" id="categories-card">
                    <h5 class="card-header">Categories</h5>
                    <div class="card-body">
                        <div class="row">
                            <ul>
                                {% for category in categories %}
                                <li class="mx-4">
                                    <a href="{{ category.get_absolute_url }}">{{ category }} ({{ category.post_set.count }})</a>
                                </li>
                                {% endfor %}
                                <li class="mx-4">
                                    <a href="/blog/category/no_category">미분류 ({{ no_category_post_count }})</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function searchPost() {
            let searchValue = document.getElementById('search-input').value.trim();
            if (searchValue.length > 1) {
                location.href="/blog/search/" + searchValue + "/";
            }
            else {
                alert('검색어('+ searchValue +')가 너무 짧습니다.');
            }
        };

        document.getElementById('search-input').addEventListener('keyup', function(event) {
            if(event.key == 'Enter'){
                searchPost();
            }
        });
    </script>

    {% include 'blog/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
</body>

</html>

blog/templates/blog/base_full_width.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}Blog{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/bootstrap/bootstrap.min.css' %}" media="screen">
    <script src="https://kit.fontawesome.com/7ec0f23614.js" crossorigin="anonymous"></script>
</head>

<body>

    {% include 'blog/navbar.html' %}

    <div class="container my-3">
        <div class="row">
            <div class="col-12" id="main-area">
                {% block main_area %}
                {% endblock %}
            </div>
        </div>
    </div>
    {% include 'blog/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
</body>

</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base_full_width.html' %}

{% load crispy_forms_tags %}

{% block head_title %}Edit Comment - Blog{% endblock %}

{% block main_area %}
    <h1>Edit Comment</h1>
    <hr>
    <form method="post" id="comment-form">{% csrf_token %}
        {{ form | crispy }}
        <br>
        <button type="submit" class="btn btn-primary float-end">submit</button>
    </form>
{% endblock %}

blog/templates/blog/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 2023 xoos0420. All rights reserved.</p>
    </div>
</footer>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
</head>
<body>
    <h1>Blog</h1>

    {% for p in posts %}
        <hr>
        <h2><a href="{{ p.get_absolute_url }}">{{ p.title }}</a></h2>
        <h4>{{ p.created_at }}</h4>
        <p>{{ p.content }}</p>
    {% endfor %}
</body>
</html>

blog/templates/blog/navbar.html
{% load socialaccount %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
        <a class="navbar-brand" href="/">Teraplatform</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="bav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/blog/">Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about_me/">Contact Us</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                        role="button" data-bs-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        {% if user.socialaccount_set.all.0.get_avatar_url %}
                            <img class="rounded-circle" width="30px" src="{{ user.socialaccount_set.all.0.get_avatar_url }}" alt="">
                        {% else %}
                            <img class="rounded-circle" width="30px" src="https://ui-avatars.com/api/?name={{ user.username }}" alt="">
                        {% endif %}
                        &nbsp;
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a href="/accounts/logout/" class="dropdown-item">Log Out</a>
                    <div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#loginModal">Log In</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="logInModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="loginModalLabel">Log In</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="row row-cols-2 mx-auto gap-2">
                        <a role="button" class="btn btn-outline-dark w-100 btn-sm" href="{% provider_login_url 'google' %}"><i
                                class="fa-brands fa-google"></i>&nbsp; Log in with Google</a>
                        <a role="button" class="btn btn-outline-dark w-100 btn-sm" href="/accounts/login/"><i
                                class="fa-solid fa-envelope"></i>&nbsp;&nbsp; Log in with Username</a>
                        <!-- <a role="button" class="btn btn-outline-dark w-100 btn-sm" href="/accounts/signup/"><i
                            class="fa-brands fa-google"></i>&nbsp; Sign Up with Google</a> -->
                        <a role="button" class="btn btn-outline-dark w-100 btn-sm" href="/accounts/signup/"><i
                                class="fa-solid fa-envelope"></i>&nbsp;&nbsp; Sign Up with E-mail</a>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ post.title }} - Blog
{% endblock %}

{% block main_area %}
<div id="post-area">
    <!-- Post title-->
    {% if post.category %}
        <span class="badge bg-primary float-end">{{ post.category }}</span>
    {% else %}
        <span class="badge bg-primary float-end">미분류</span>
    {% endif %}

    <h1 class="fw-bolder mb-1">{{ post.title }}</h1>
    <h5 class="text-muted">{{ post.hook_text }}</h5>

    <!-- Author -->
    <p class="lead">
        by 
        <a href="#">{{ post.author | upper }}</a>
    </p>
    <hr>

    {% if user.is_authenticated and user == post.author %}
    <a class="btn btn-primary btn-sm float-end" href="/blog/update_post/{{ post.pk }}/" role="button"><i class="fas fa-pen"></i>  Edit Post</a>
    {% endif %}

    <!--Date/Time-->
    <p>{{ post.created_at }}</p>
    <hr>

    <!-- Preview image -->
    {% if post.head_image %}
    <img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="{{ post.tile }} head_image">
    {% else %}
    <img class="img-fluid rounded" src="https://picsum.photos/seed/{{ post.id }}/1000/400" alt="random_image">
    {% endif %}
    <hr>

    <!-- Post content-->
    <p>{{ post.get_content_markdown | safe }}</p>
    {% if post.file_upload %}
    <a href="{{ post.file_upload.url }}" class="btn btn-outline-secondary" role="button" download="">download:
        {% if post.get_file_ext == 'csv' %}
        <i class="fa-solid fa-file-csv"></i>
        {% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
        <i class="fa-solid fa-file-excel"></i>
        {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
        <i class="fa-solid fa-file-word"></i>
        {% elif post.get_file_ext == 'pdf'%}
        <i class="fa-solid fa-file-pdf"></i>
        {% elif post.get_file_ext == 'ppt' or post.get_file_ext == 'pptx' %}
        <i class="fa-solid fa-file-powerpoint"></i>
        {% elif post.get_file_ext == 'zip' or post.get_file_ext == '7z' or post_get_file_ext == 'tar' %}
        <i class="fa-solid fa-file-zipper"></i>
        {% else %}
        <i class="fa-solid fa-file"></i>
        {% endif %}
        {{ post.get_file_name }}
    </a>
    {% endif %}

    <hr>
</div>

<div id="comment-area">
    <!-- Comments Form-->
    <div class="card my-4">
        <h5 class="card-header">Leave a comment:</h5>
        <div class="card-body">
            {% if user.is_authenticated %}
            <form id="comment-form" method="POST" action="{{ post.get_absolute_url }}new_comment/">
                {% csrf_token %}
                <div class="form-group">
                    {{ comment_form | crispy }}
                </div>
                <div class="d-flex justify-content-end mb-4">
                    <button type="submit" class="btn btn-primary">submit</button>
                </div>
            </form>

            {% else %}
            <div class="mb-4">
                <a role="button" class="btn btn-outline-dark btn-block w-100 btn-sm" href="#" data-bs-toggle="modal" data-bs-target="#loginModal">Log in and leave a comment</a>
            </div>
            {% endif %}

            {% if post.comment_set.exists %}
                {% for comment in post.comment_set.iterator %}
                    <!-- Single comment-->
                    <div class="d-flex" id="comment-{{ comment.pk }}">
                        <div class="flex-shrink-0">
                            <img class="rounded-circle flex-shrink-0" src="{{ comment.get_avatar_url }}" alt="{{ comment.author }}" width="60px">
                        </div>

                        <div class="ms-3">
                            <div class="fw-bold">
                                {{ comment.author.username }} &nbsp;&nbsp;<small class="text-muted">{{ comment.created_at }}</small>
                            </div>
                            <p>{{ comment.content | linebreaks }}</p>
                            {% if comment.created_at != comment.modified_at %}
                                <p class="text-muted"><small>Updated: {{ comment.modified_at }}</small></p>
                            {% endif %}
                        </div>

                        {% if user.is_authenticated and comment.author == user %}
                            <div class="ms-auto">
                                <a role="button" class="btn btn-primary btn-sm"
                                id="comment-{{ comment.pk }}-update-btn" href="/blog/update_comment/{{ comment.pk }}/">Edit</a>
                                <a role="button" class="btn btn-danger btn-sm"
                                id="comment-{{ comment.pk }}-delete-modal-btn"
                                href="#" data-bs-toggle="modal" data-bs-target="#deleteCommentModal-{{ comment.pk }}">Delete</a>
                            </div>

                            <!-- Modal -->
                            <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" role="dialog" aria-labelledby="deleteCommentModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="deleteModalLabel">Are you Sure?</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <del>{{ comment | linebreaks }}</del>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancle</button>
                                            <a role="button" class="btn btn-danger" href="/blog/delete_comment/{{ comment.pk}}/">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <hr>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base_full_width.html' %}

{% load crispy_forms_tags %}

{% block head_title %}created Post - Blog{% endblock %}

{% block main_area %}
    <h1>Create New Post</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form | crispy }}
        <br>
        <button type="submit" class="btn btn-primary float-end">submit</button>
    </form>
    {{ form.media }}
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block main_area %}

{% if user.is_authenticated %}
{% if user.is_superuser or user.is_staff %}
<a class="btn btn-primary btn-sm float-end" href="/blog/create_post/" role="button">
    <i class="fas fa-pen"></i>&nbsp;&nbsp;New Post</a>
{% endif %}
{% endif %}

<h1>Blog
    {% if search_info %}
        <small class="text-muted">{{ search_info }}</small>
    {% endif %}
    {% if category %}
        <span class="badge bg-primary">{{ category }}</span>
    {% endif %}
</h1>
{% if post_list.exists %}

{% for p in post_list %}
<!-- Blog post-->
<div class="card mb-4" id="post-{{ p.pk }}">
    {% if p.head_image %}
    <img class="card-img-top" src="{{ p.head_image.url }}" alt="{{ p }} head_image">
    {% else %}
    <img class="card-img-top" src="https://picsum.photos/seed/{{ p.id }}/850/350" alt="random_image">
    {% endif %}

    <div class="card-body">
        {% if p.category %}
        <span class="badge bg-primary float-end">{{ p.category }}</span>
        {% else %}
        <span class="badge bg-primary float-end">미분류</span>
        {% endif %}

        <h2 class="card-title h4">{{ p.title }}</h2>

        {% if p.hook_text %}
        <h5 class="text-muted">{{ p.hook_text }}</h5>
        {% endif %}

        <p class="card-text">{{ p.get_content_markdown | truncatewords_html:45 | safe }}</p>
        <a class="btn btn-primary" href="{{ p.get_absolute_url }}">Read more →</a>
    </div>

    <div class="card-footer text-muted">
        Posted On {{ p.created_at }} by
        <a href="#">{{ p.author | upper }}</a>
    </div>

</div>
{% endfor %}
{% else %}
<h3>아직 게시물이 없습니다</h3>
{% endif %}

{% if is_paginated %}
<!-- Pagination -->
<ul class="pagination justify-content-center mb-4">
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&larr; Older</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">&larr; Older</a>
        </li>
    {% endif %}

    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Newer &rarr;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">Newer &rarr;</a>
    </li>
    {% endif %}
</ul>
{% endif %}
{% endblock %}

blog/templates/blog/post_update_form.html
{% extends 'blog/base_full_width.html' %}

{% load crispy_forms_tags %}

{% block head_title %}Edit Post - Blog{% endblock %}

{% block main_area %}
    <h1>Edit</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form | crispy }}
        <br>
        <button type="submit" class="btn btn-primary float-end">submit</button>
    </form>
    {{ form.media }}
{% endblock %}

blog/templates/blog/single_post_page.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ post.title }} - Blog</title>
</head>
<body>
    <nav>
        <a href="/blog">Blog</a>
    </nav>
    <h1>{{ post.title }}</h1>
    <h4>{{ post.created_at }}</h4>
    <p>{{ post.content }}</p>
    <hr>
    <h3>여기 댓글이 들어오는 자리</h3>
</body>
</html>